### PR TITLE
Added configurable array of included language files for generator

### PR DESCRIPTION
**Pull request by a-komarev**
I've added configuration file for your package.

Right now there could be defined list of language files which should be included in javascript output.

Checks are done via separate method for easier extending functionality in future:
- [define excludes via console command](https://github.com/rmariuzzo/Laravel-JS-Localization/pull/41)
- add ability to include only exact messages in language files, not the whole files:

```php
'messages' => [
    'passwords.reset',
    'pagination.next',
    'pagination.previous',
],
```

2 more cases covered in unit tests, code cleaned up and formatted in PSR-2 (because it's standard since [Laravel 5.1](https://laravel.com/docs/master/releases#laravel-5.1)).

### CODE REVIEW

**Comment by rmariuzzo** [comment]
Hey @a-komarev!

I'm very grateful for this addition. I have been inactive in past month because [I'm sick](http://gothodgkin.tumblr.com). Right now, I'm feeling better and I'm ready to take and improve this project.

Do you time to update your PR with develop and push the changes? Otherwise, I will resolve the conflict myself.

**Comment by rmariuzzo** [comment]
@a-komarev also, I can see that your PR is an improvement made over #41. Is that correct?

**Comment by rmariuzzo** [comment]
Sorry to bug you @a-komarev... there are some conflicts. Make sure to updated `develop` branch please.

**Comment by a-komarev** [comment]
I've broke my repository and forgot about it. WIP on recreation all from scratch and without conflicts.

**Pull request closed without merging**
