### PR TITLE
add feature --no-lib

### PR DESCRIPTION
**Pull request by ardani**
This PR to solve issue #79 with add feature option `--no-lib` export without Library Lang.js

### CODE REVIEW

**Comment by a-komarev** [comment]
@ardani thanks! It will be good to write unit tests for it.

**Comment by ardani** [comment]
@a-komarev  sure, i try write unit test for it

**Comment by ardani** [comment]
hi @a-komarev testing added, please check it. thanks

**Comment by a-komarev** [comment]
@ardani thanks for the tests. I've synced it with latest development changes. Waiting for @rmariuzzo to review & merge the changes.

**Pull request merged**
