### PR TITLE
Support laravel 6

### PR DESCRIPTION
**Pull request by cams5792**

### CODE REVIEW

**Comment by conselio** [comment]
I need it !

**Comment by aaronmeder** [comment]
🙏🏻I have the same issue not being able to upgrade to Laravel 6 because of it.
Verified that the changes suggested in this PR work in my env 👍🏻

**Comment by rmariuzzo** [comment]
I'm away from my laptop right now. I will probably check later today.

**Comment by cams5792** [comment]
@rmariuzzo did you check it ?

**Comment by rmariuzzo** [comment]
Not yet, I need to revisit CI errors... If anyone can make it pass would be appreciated. Will try to make some time tonight.

**Comment by IvanBernatovic** [comment]
The issue lies in this line in .travis.yml
"if [[ `php -v` =~ "PHP 7.2" || `php -v` =~ "PHP 7.3" ]]; then yes | pecl install mcrypt-1.0.1; fi"

The error message in travis logs is:

> pecl/mcrypt requires PHP (version >= 7.2.0, version <= 7.3.0, excluded versions: 7.3.0), installed version is 7.3.9
> 
> No valid packages found

I think the solution is to change the problematic mcrypt version to 1.0.2 (`pecl install mcrypt-1.0.2`) which fully supports PHP 7.3.

@cams5792 Can you also change travis.yml in your PR so we can check if build is successful then?

**Comment by cams5792** [comment]
Thanks @IvanBernatovic it works

**Comment by IvanBernatovic** [comment]
@rmariuzzo Since everything is approved and Travis checks are passing can you please merge this and release it?

**Comment by rmariuzzo** [comment]
Ok, give me a few minutes

**Comment by rmariuzzo** [comment]
I just released a new version with the changes introduced by you in this PR: https://packagist.org/packages/mariuzzo/laravel-js-localization#v1.5.0

Can you all give a test?

**Comment by IvanBernatovic** [comment]
It installs/updates successfully in Laravel 6 app and `php artisan lang:js` works as expected.

**Comment by cams5792** [comment]
https://github.com/rmariuzzo/Laravel-JS-Localization/pull/134#issuecomment-529901339
the same for me

**Pull request merged**
