### PR TITLE
Fix windows directory separator in generator

### PR DESCRIPTION
**Pull request by a-komarev**
Related to #65

### CODE REVIEW

**Comment by a-komarev** [comment]
@rmariuzzo I don't have any Windows machines, so I'm waiting to somebody to test it. Feel free to merge it.

**Comment by rmariuzzo** [comment]
I could test it, but it will not be soon. I'm on my way home from the
hospital. I will update you later.

**Comment by oliski** [comment]
Nope, does not work :)

Problem that in config, it is something like: folder/file

However, in isMessagesExcluded,  $filePath is  "folder\file". 

It is enought if you do wollowing in the isMessagexExcluded file:  $filePath = str_replace(DIRECTORY_SEPARATOR,'/',$filePath);

**Comment by olelis** [comment]
Here, check my pull request: 
https://github.com/rmariuzzo/Laravel-JS-Localization/pull/67

**Comment by a-komarev** [comment]
@rmariuzzo yeah, sorry, forgot to close it.

**Pull request closed without merging**
