### PR TITLE
Laravel 9 compatibility

### PR DESCRIPTION
**Pull request by ahoiroman**
This should add compatibility to Laravel 9

### CODE REVIEW

**Review by ahoiroman — COMMENTED** [review]
Added 7.0 and reviewed

**Review by rmariuzzo — APPROVED** [review]

**Comment by rmariuzzo** [comment]
I will push the new version soon.

**Comment by ahoiroman** [comment]
Thanks - that would be amazing :-)

**Comment by rmariuzzo** [comment]
Will do it in 1hr. Yesterday, I was in the hospital.

**Comment by ahoiroman** [comment]
No problem at all. I really appreciate your work :-)

**Comment by rmariuzzo** [comment]
Finally, was able to publish the [new release](https://github.com/rmariuzzo/Laravel-JS-Localization/releases/tag/v1.9.0).

**Pull request merged**
