### PR TITLE
Script created to fetch and copy lang.js into repo.

### LINKED ISSUE #42: lang.js not found because of git-submodules.
lang.js is not exist.

how can i?

### PR DESCRIPTION
**Pull request by rmariuzzo**
This PR fixes #42. I'm creating a bash script that will need to be run before each release. This script will fetch the `lang.js` git modules and then copy it into the repo.

### CODE REVIEW

**Comment by rmariuzzo** [comment]
What do you think @vluzrmos and @a-komarev ?

**Comment by a-komarev** [comment]
Only developers should run this command to refresh dependency?

Haven't faced this before, but maybe there is a way to use composer functionality somehow to automate it? Something like [scripts section](https://github.com/laravel/laravel/blob/master/composer.json#L31-L46)

**Comment by rmariuzzo** [comment]
Good idea @a-komarev! I will give it a try and will keep you posted in this thread.

**Comment by rmariuzzo** [comment]
@a-komarev I did what you suggested with Composer's script. Super clean 👌

**Comment by a-komarev** [comment]
@rmariuzzo looks much better :+1: 

Is there any reason why you've dropped 5.1 support?

**Comment by rmariuzzo** [comment]
It wasn’t intentional, I will play today with the support for 4.2, 5.0-5.3. I will ensure to support all these versions before the next release that I wish to do in this week. Thanks for the observation.

**Comment by rmariuzzo** [comment]
This fixes #42

**Pull request merged**
