### PR TITLE
_testInterval

### PR DESCRIPTION
**Pull request by vluzrmos**

### CODE REVIEW

**Comment by vinicius73** [comment]
Greate!

**Comment by vluzrmos** [comment]
@rmariuzzo please

**Comment by vluzrmos** [comment]
@rmariuzzo man?

**Comment by rmariuzzo** [comment]
It looks OK for me. Are there any tests @vluzrmos ?

**Comment by vluzrmos** [comment]
I don't know how to test js files. But it works fine on my project

**Comment by rmariuzzo** [comment]
Cool, that’s fair enough. :) 


Rubens Mariuzzo
rubens@mariuzzo.com

**Comment by vluzrmos** [comment]
I'm improving that....

**Comment by rmariuzzo** [comment]
Cool!

**Pull request closed without merging**
