### PR TITLE
Laravel 5 compatibility

### PR DESCRIPTION
**Pull request by sboo**

### CODE REVIEW

**Comment by rmariuzzo** [comment]
Awesome @sboo and @xAockd ! I would like to include you two guys as collaborators in this project, what do you think?

**Comment by sboo** [comment]
I don't mind, I'm grateful you made this! I'm glad to help out where I can

**Comment by rmariuzzo** [comment]
@sboo do you want to share publicly an email address in the `composer.json` file?

**Comment by rmariuzzo** [comment]
All done! I appreciate all your support, that was encouraging. However, there's still an issue with `phpunit` and the changes with packages in Laravel 5. I'm gonna fix this later.

**Comment by sboo** [comment]
@rmariuzzo you can add ramon.ackermann@sboo.eu

**Comment by rmariuzzo** [comment]
Thanks!

**Pull request merged**
