### PR TITLE
Adding json only output option

### PR DESCRIPTION
**Pull request by Zakay**
In order to provide our apps with language keys/message/strings we needed a clean json output.
This is the cleanest way of sharing language between different clients, just plain json.

### CODE REVIEW

**Comment by Sealos** [comment]
+1.0

**Comment by rmariuzzo** [comment]
@a-komarev and @vluzrmos can you double check this contribution? I will check it tomorrow. However, the idea sound appealing since Laravel also supports JSON file for localization.

The failing check from Travis is because HHVM is not supported on Precise (will need to address this).

**Comment by a-komarev** [comment]
@rmariuzzo I'm not at home at this moment, will be able too look on it this evening I suppose. We could remove HHVM checks since it's support was dropped from Laravel.

**Comment by a-komarev** [comment]
Looks good to me.

**Comment by Sealos** [comment]
Any updates?

**Comment by rmariuzzo** [comment]
@Sealos sorry for the long delay, will release an update in 1-2 days.

**Pull request merged**
